### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by thamerlan** [cybertec-postgresql/safe-backup#3]
pgpre.sh fails with 0 error code. 
```
$ ./pgpre.sh 
Backup failed
backup starting location: Time: 0.218 ms
echo $?
0
```

Any ideas?

P.s.
postgres 16.3, Ubuntu 22.04.4 LTS

**Comment by laurenz** [comment]
Looking into my crystal ball, I see that you have `\timing on` in your `.psqlrc` file.
I guess the solution is to disable reading the `.psqlrc` file. I will make that happen.

**Comment by laurenz** [comment]
Could you check if that fixes the problem?

**Comment by thamerlan** [comment]
> Could you check if that fixes the problem?

Yes, thanks. The crystal ball doesn't lie. 

```
$ mv ~postgres/.psqlrc ~postgres/.psqlrc.backup
$ ./pgpre.sh
backup starting location: 0/8000028
```

P.s.
Zero error code confused me.

**Comment by thamerlan** [comment]
To fix the issue just replace
`coproc PSQL { psql -Atq; }`
with
`coproc PSQL { psql -AtqX -d 'application_name=hot_backup_session'; }`
in both files.

**Comment by laurenz** [comment]
That's exactly what my patch d2a64e0a933bfb4be505fc1612f42282b411e3db does.

So I take it that this issue can stay closed, right?

**Comment by thamerlan** [comment]
> That's exactly what my patch [d2a64e0](https://github.com/cybertec-postgresql/safe-backup/commit/d2a64e0a933bfb4be505fc1612f42282b411e3db) does.
> 
> So I take it that this issue can stay closed, right?

Yes, it is ok. 

P.s. 
final touch:
it will be nice to do:
`coproc PSQL { psql -AtqX -d 'application_name=hot_backup_session'; }`
to be able to control/monitor active session by app name (at least in pgpre.sh).

**Comment by laurenz** [comment]
Thanks for the suggestion.

I'll leave it as it is &mdash; after all, these scripts are usually not a complete solution. You'd want to adapt them to your needs so that `backup_label` is put where it belongs, for example.
So this code is more of a serving suggestion that a product that's ready for use as it is, and detailed embellishments like your suggestion are left as an exercise to the reader. I expect that many people use a dedicated backup user and can recognize the backup session from the username.
